name: Django CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Run docker
      run: |
        make start_docker
        docker-compose run web python manage.py test
#        docker-compose exec -T web sh python manage.py test
